### ISSUE TITLE
windows ui "reboot-visor" handling

### ISSUE THREAD

**Issue by 4rchim3d3s** [skycoin/skywire#1098]
**Describe the bug**
When using skywire app on windows the following error comes up when trying to reboot the visor.

**Environment information:**

- OS: Windows, v0.6.0-rc2

**Steps to Reproduce**

1. Go to Menu 
2. Click on "reboot visor"

**Actual behavior**
![image](https://user-images.githubusercontent.com/50741854/153772755-6250b916-3a18-4249-8569-ec61bf45ebaf.png)

**Expected behavior**
either restart the application or return a message like : "This function doesn't work on windows"

**Additional context**

**Possible implementation**
Hints to fix the bug.

**Comment by 0pcom** [comment]
I expect that most of the buttons to manipulates the visor process from the hypervisor UI is only going to work on linux.

In the second place i'm not sure how its being stopped from the UI on linux or if it works with the systemd services or robustly depending on how the process was started.

I would like at least more documentation of the hypervisor.

@4rchim3d3s when you see something like this, i also suggest checking the skywire-cli to see if we have a way to do it from cli for at least the local visor.

Because we do have some feature parity issues currently between visor and cli and that would be something to take into consideration along with the underlying issue.

**Comment by jdknives** [comment]
@4rchim3d3s thanks for the issue. Will handle that in the next release.

**Comment by mrpalide** [comment]
In addition to the reboot button, the update button should not be available in Windows.
