### ISSUE TITLE
Merged binary for Windows and Mac

### ISSUE THREAD

**Issue by mrpalide** [skycoin/skywire#1769]
**Feature description**
As we implemented recently merged binary for linux, then be good if we have same situation for Windows and Mac.

**Comment by mrpalide** [comment]
Based on this comment [(here)](https://github.com/sirupsen/logrus/issues/992) from logrus collaborator, the `github.com/sirupsen/logrus/hooks/syslog` package could not build on Windows at all, so we don't have any chance to have skywire-deployment merged binary file on Windows.
So we keep Windows and MacOS build/binary/installer file at current logic and continue with separated apps.

**Comment by 0pcom** [comment]
it should still be possible to compile https://github.com/skycoin/skywire/blob/master/cmd/skywire/skywire.go on both windows and mac

If it still won't build because of this

"The github.com/sirupsen/logrus/hooks/syslog package will not build on Windows, Plan9, and nacl because the entirety of it is behind a set of [build constraints](https://golang.org/pkg/go/build/#hdr-Build_Constraints) (via [build tags](https://github.com/sirupsen/logrus/blob/master/hooks/syslog/syslog.go#L1)) that prevent it from being compiled on those platforms."

Then we should simply remove the syslog because it's totally unused AFAIK
