### ISSUE TITLE
TestConn Future timeouts fails

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#201]
**Describe the bug**
When runnning `make check` on the RPi I get the logs attached. Note that it only happens on the Pi but it happens consistently there, maybe due to low performance of it. Originally logged here : https://github.com/SkycoinProject/skywire-mainnet/pull/199

**Environment information:**
- OS: e.g. Raspbian Buster
- Platform: Linux 4.19.75-v7l+ armv7l 
- Running with Go 1.13.5**

**Comment by nkryuchkov** [comment]
I was able to reproduce it on a laptop with `amd64`.

**Comment by evanlinjin** [comment]
Yeah this is going to be a hard one to tackle.

**Comment by nkryuchkov** [comment]
Due to the lower performance of RPi, `TestRouteGroup_TestConn` runs on it for around one minute. All `nettest.TestConn` tests have a one-minute timeout (https://github.com/golang/net/blob/master/nettest/conntest.go#L55), so after one minute `RouteGroup` gets closed and test fails. This means that the test fails because of implementation performance, not because of a bug. However, we might need to raise an issue for improving implementation performance.

**Comment by nkryuchkov** [comment]
The issue still presents after solving https://github.com/SkycoinProject/skywire-mainnet/issues/197.

**Comment by nkryuchkov** [comment]
It also happens in `TravisCI`: https://travis-ci.com/github/SkycoinProject/skywire-mainnet/jobs/311605717

**Comment by nkryuchkov** [comment]
Updated TravisCI link: https://travis-ci.com/github/skycoin/skywire/jobs/311605717
