### ISSUE TITLE
Cannot login to manager UI

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#238]
**Describe the bug**
When trying to login to the manager UI with `enable_auth` set to `true`, it is possible to create the user account, but the actual login is not working. 

**Environment information:**

- OS: MacOS

**Steps to Reproduce**

1. Checkout develop branch with changes made here: https://github.com/SkycoinProject/skywire-mainnet/pull/236
2. Generate hypervisor config with `hypervisor config-gen -rt`
3. Run `hypervisor` 
4. Go to `localhost:8080`
5. Create Password for User account by clicking Configure Initial Launch
6. Try to login with the password entered before

**Comment by Senyoret1** [comment]
The problem happens because `localhost:8080` is opened with http instead of https.

The login operation in fact is finished successfully and the hypervisor returns an secure session cookie for being able to access the other parts of the manager. However, as the session cookie is secure and the url is a http one, when the manager tries to make the next requests (which is made to `/api/user`) the web browser does not send the session cookie, so the hypervisor responds with `{"error":"session cookie is either non-existent, expired, or ill-formatted"}` and the manager immediately returns to the login page, thinking that the session is expired.

**Comment by jdknives** [comment]
Fixed by #243
