### ISSUE TITLE
Build and run on Windows

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#343]
**Feature description**

It would be nice to have (although not essential) to be able to run and build mainnet on Windows. Currently, the Sirupsen package prevents that as it uses build tags that prevent it from building on Windows.

**Comment by Darkren** [comment]
Building part will be fixed by #356 . However some issues will still need to be addressed. We'll need proper readme on how to run this. binaries are not being built with `.exe` etension which prevents OS from simply running it. app pids management via file won't work. args aren't being passed to apps. just writing all this not to forget
