### ISSUE TITLE
Visor UI

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#352]
**Feature description**

Visor could expose a very minimal UI to the user on localhost. The UI would allow to add transports, set the VPN configuration and allow to toggle on and off the VPN client. This way, we would allow users to use the Skywire VPN more easily without using the CLI. Later on, we could distribute a visor binary that works similarly to current VPN clients.

**Is your feature request related to a problem? Please describe.**
Average users currently cannot use the VPN client without using the CLI.

**Comment by evanlinjin** [comment]
In addition to this issue, right now the whole communication process between visor to hypervisor to manager is not the most ideal. We need to maintain two *hops* in the channel of communication:
1. Visor to hypervisor is by RPC via dmsg.
2. Hypervisor to Manager UI is via RESTful API over HTTP.

This results in us having to maintain two sections of code for a single line of communication between visor and Manager UI.

A possible solution would be to ***combine*** the Manager UI and Hypervisor into a single concept. The old hypervisor backend will be altered, and compiled with [GopherJS](https://github.com/gopherjs/gopherjs).

For the frontend developer, instead of write RESTful calls in the frontend, they would be interacting with [DOM Events](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Events) triggered by the GopherJS-compiled code.

The visor will host this frontend code.

This solution kills two birds with one stone:
1. Make development easier with less codebase to maintain and debug.
2. All visors can hence, provide an UI experience be default.

**Comment by jdknives** [comment]
This would also solve the long term issue of how to distribute the VPN client to users. Because as a user I want to be able to:

1. Manage my nodes
2. Use the node functionality (i.e. use the VPN client)

It would be less than ideal if that was split up between two separate interfaces/applications. Or maybe this could be desired depending on design. I will speak to @SkycoinSynth about it.

**Comment by jdknives** [comment]
Fixed on `feature/v0.0.4` branch.
