### ISSUE TITLE
Display local IP

### ISSUE THREAD

**Issue by 4rchim3d3s** [skycoin/skywire#389]
**Feature description**

It would be helpful to see the local ip-address of the visor inside the details.
Also for skychat it would be nice to have a hyperlink inside the visor-app-list to the ip-address:port-of-skychat. 
For example a world-logo like in the picture below.
So a hyperlink column for applications where you need web-interface.

**Is your feature request related to a problem? Please describe.**
Tried skychat and had no idea which pubkey/visor belongs to which ip-address:8001 without doing further research.

![image](https://user-images.githubusercontent.com/50741854/83611004-9e646d00-a580-11ea-9e14-f25193b1b9f4.png)

**Comment by jdknives** [comment]
@4rchim3d3s good point. Will see what is feasible with the hyperlink. The way the Skyminer is setup only one of the nodes Skychat UI can be accessed easily. Displaying the local IP should be fine.

**Comment by Senyoret1** [comment]
At this momment the UI is not able to show the local IP because the API does not return it. For example, using the integration enviroment, the `/api/visors/{pk}` API endpoint returns in the `tcp_addr` property something like `024ec47420176680816e0406250e7156465e4531f5b26057c9f6297bb0303558c7:49153`.

Because of this, at this moment there is also no reliable way to create a link for opening the Skychat app.

**Comment by jdknives** [comment]
Tackled on the backend with #716.

**Comment by jdknives** [comment]
Fixed
