### ISSUE TITLE
There should be a way to identify common errors returned by Skywiremob

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skywire#516]
**Feature description**
There are multiple reasons that may make the startup procedure of Skywiremob fail, but some of them are especially important, because are frequent and special instructions should be shown to the user. A way to identify those problems should be added.

**Is your feature request related to a problem? Please describe.**
When starting a visor, Skywiremob returns error messages that are not very good for the UI. One example is when the user enters a wrong password, in that case Skywiremob returns `got status 4 (Forbidden) from the server`. Other case is when it is not possible to connect to the remote VPN server, the error msg in that case is `failed to dial VPN server: route finder: transport not found`.

**Describe the solution you'd like**
Instead of showing those messages, it would be better if Skywiremob returns something identifiable by the UI, so the UI is able to recognize them and show better indications to the user. It is clear that not all errors can be identified, but at least the “server not found” and “wrong password” errors should be easy to identify.

A specific string should be added to the error msg, so the UI identifies it and shows a better error message.

**Describe alternatives you've considered**
This could be done right now without changes, as the UI could have an `if` just with the error messages described above, but there are 2 problems:

1.	There may be more error messages for the same type of error, as there is no a list. For example, maybe Skywiremob returns a different error if the remote visor is online but the VPN server app on it is stopped, but for the end user that continues being a “server offline” problem.
2.	Nothing guarantees that the error msgs will continue to be the same in future versions.

**Comment by Senyoret1** [comment]
Another error that should be easily identifiable is when the visor is not able to connect with the dmsg network.

**Comment by Darkren** [comment]
hey there @Senyoret1 . there's no easy way to identify if visor couldn't connect to the dmsg network, since it keeps on reconnecting in the background. if it's crucial we'll need to deal with it separately. other than that I pushed changes to the original PR. I decided to stick with the error codes. this way you may define proper error strings yourself and maintain them. full error list is present in the `skywiremob.go` file, in the very beginning. I tried to give errors self explanatory names, but if you need details on some, please let me know. all these errors are exposed to the mobile app, so you may simply compare it in the Java code. if anything else is needed on this ticket, please let me know

**Comment by Senyoret1** [comment]
I made the changes in the Android app and was able to make it work well. The changes now allow to translate the error messages and to identify if the code should react differently for the error, but there are still some changes that would be good to make.

The problem with just returning error codes is that there are now a lot of unidentifiable errors, which may make it very difficult to know what went wrong. One important example is when the user enters an incorrect password, in which case Skywiremob was returning `got status 4 (Forbidden) from the server` as the error message, as said in the original description of the issue. The problem with the recent changes is that there is no error code for knowing when the user entered a wrong password, so now the app can only show a generic msg used for all unknown errors, which is even less useful than the old error msg.

In this case, it would be good to have specific error codes for the errors described in the first messages: incorrect password and unreachable remote visor. However, just doing this may leave other important errors unattended, which may end being equally problematic. Because of this, maybe it would be good to return not only an error code, but also the error string that was previously being returned. That way the app would be able to show better messages during known errors and the string generated by the visor when the error is unknown. That way it should be easier to identify the unknow errors.

**Comment by Darkren** [comment]
@Senyoret1 I see. There're these codes:
- ErrCodeFailedToSaveTransport
- ErrCodeVPNServerUnavailable
Both happen when remote visor is unavailable. But happen on different steps, also I think first one may happen due to some other reasons, but not sure. So I differentiated these.

I'll add specific code for the incorrect password.

I may return object with code and error message if that makes sense. I just think that future localization will be troublesome with such approach, so I added only codes initially. Cause error messages coming from skywiremob will be in english anyway. Should I return error message along with the code nevertheless?

**Comment by Senyoret1** [comment]
Yes, please return both. The main reason is that in the future we may have several users reporting the error message assigned to `ErrCodeUnknown` and we will not have an easy way to know if all those users are having the same problem or not, or exactly what is happening, which could start a support hell. However, if we also show the English error msg, maybe the user will not be able to use it to know how to solve the problem, but the support team may be able to do something with it.

**Comment by Darkren** [comment]
@Senyoret1 sure, will do

**Comment by Senyoret1** [comment]
@Darkren I created error messages for the codes currently returned by Skywiremob, with some indications about the possible causes. However, I cold have made mistakes and some messages may contain imprecise or misleading information, so I would really appreciate if you can take a quick look when you have some time. The messages are in https://github.com/Darkren/skywire-mainnet/pull/1/commits/88f61ed01c30349749f954a76f1c76c21f57dea8

**Comment by Darkren** [comment]
@Senyoret1 hey there. please check out latest commits I've pushed to the PR. Returning error message and the code along now
