### ISSUE TITLE
'Copy hypervisor pubkey to clipboard' function in hypervisor UI

### ISSUE THREAD

**Issue by 4rchim3d3s** [skycoin/skywire#562]
**Feature description**

It would be helpful when setting up new visors to easily access the pubkey of the hypervisor via
a copy to clipboard function inside the hypervisor UI

**Is your feature request related to a problem? Please describe.**
No, it would just be simpler instead of opening the config file

**Describe the solution you'd like**
Like described above. I think the function could be implemented in the dropdown menu in the right upper corner

**Comment by jdknives** [comment]
@4rchim3d3s also fixed by next release. As the hypervisorUI will be exposed by a regular visor, you can just copy that visors key. Attached a preview for reference. 

<img width="1440" alt="Bildschirmfoto 2020-11-19 um 21 53 36" src="https://user-images.githubusercontent.com/36450093/99717197-c48bb400-2ab1-11eb-9cd9-4957c16dfdfd.png">
