### ISSUE TITLE
Add new flags to hypervisor app management

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#609]
**Feature description**

Two new flags will be added to the VPN with the next release. 

- killswitch
- secure

Both accept boolean values. They need to be changeable via the app management interface in the UI. 

Reference PRs

- https://github.com/skycoin/skywire/pull/608/
- https://github.com/skycoin/skywire/pull/598

**Comment by Senyoret1** [comment]
I added the options to the UI, but for saving the changes, I need to send the new setting to the `PUT /visors/{pk}/apps/{app}` API endpoint, which is how the manager currently saves the changes for all app settings. The problem is that the endpoint currently does not accept the killswitch and secure options. After making the endpoint able to receive those settings, I think it will be possible to make the final changes.

**Comment by jdknives** [comment]
@Senyoret1 just merged #618 so you should be able to go ahead.
