### ISSUE TITLE
Build from vendor folder

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#682]
**Feature description**

We should build our binaries from the vendor folder instead of relying on go mods internal vendor. 

**Is your feature request related to a problem? Please describe.**
Synth requested it because in China it is often a pain to download dependencies. So once you are in possession of the source code including the vendor folder you should be able to build easily from that folder. Also there may be security issues potentially.

**Comment by i-hate-nicknames** [comment]
I believe since 1.14 go build uses vendor directory by default. Our `build` makefile target though involves not just building but also fetching new dependencies into vendor/. To avoid doing this one can build via `make bin host-apps`. I was able to build with no internet connection and empty go mod cache.
