### ISSUE TITLE
Transport briefly shown as created when dialing fails

### ISSUE THREAD

**Issue by jdknives** [skycoin/skywire#817]
**Describe the bug**
When a user dials a `tp` from the hypervisor that cant be established, the transport is shown in the background (as down, indicated by red circle) for a brief period. Only when the hypervisor dials the next time for `visorDetails`, does the transport get removed from frontend because it never was established. That is confusing, as the frontend shows transport as existing and returns a success message.

**Comment by Senyoret1** [comment]
I made some tests and the problem appears to be in the backend. If you use the UI for creating a new transport using the address of an offline node, the UI try to create it calling `POST /api/visors/{pk}/transports` and the server will return 200, so the UI will show no errors. After that, the UI calls `GET /api/visors/{pk}/summary` to get the updated data about the visor and that call includes the new transport in the response, so the UI shows it.

I think that maybe the first call should return an error, to show an error msg, but the second call is the one that in any case should not include the transport, because the UI could call it at any moment and that would result in the UI showing the transport.

**Comment by alexadhy** [comment]
On latest `develop` (commit a6697f9e0d12a41cce526f6f94daa1c53bed19a0), I can no longer replicate this issue on the backend side.
