### ISSUE TITLE
Release Sources Build - Git Error

### ISSUE THREAD

**Issue by Asgaror** [skycoin/skywire#875]
**Describe the bug**
Building the sources from release produces error messages although the build succeeds:
`fatal: not a git repository (or any of the parent directories): .git`

**Environment information:**
- OS: Linux 5.11.0-27-generic x86_64 

**Steps to Reproduce**

1. Download sources [https://github.com/skycoin/skywire/archive/refs/tags/v0.4.2.zip](https://github.com/skycoin/skywire/archive/refs/tags/v0.4.2.zip)
2. Extract and enter directory
3. Execute `make build`
4. See error: `fatal: not a git repository (or any of the parent directories): .git`

**Actual behavior**
Building the source should not produce any error messages even if there is no initialized `.git` repository.

**Expected behavior**
`make build` of sources from any release should not produce the error message.

**Additional context**
The `Makefile` commands in:
- [line 11](https://github.com/skycoin/skywire/blob/5f47d506996e0f858ba9626604257e8baf0ebf97/Makefile#L11) and 
- [line 16](https://github.com/skycoin/skywire/blob/5f47d506996e0f858ba9626604257e8baf0ebf97/Makefile#L16) 
appear to be causing this bug.

**Comment by 0pcom** [comment]
I identified this issue.

The context of it's occurrence is in any build which uses the source archive for a particular versioned release rather than just the latest commits on whichever branch. It's a smaller download to use the source archive, and the build is more consistent.

[the skywire AUR PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=skywire) 

My solution above is to manually version to the tag version in the build, with the necessary lines borrowed (and modified) from the Makefile.

The general solution would be to specifically alter how the versions are generated in the release archive- in order to not have to use `git` for the versioning. I don't think it's bad to use git for versioning, nor do i think it should stop being used; but it remains unclear how to sufficiently reduce the size of the .git folder to the point it would not needlessly bloat the archive for the simple purpose of supplying the version.
