### ISSUE TITLE
The state info of the vpn-client app is a bit erratic

### ISSUE THREAD

**Issue by Senyoret1** [skycoin/skywire#940]
**Describe the bug**
When the vpn-client app is stated, the API returns various statuses before returning `1` (which means it is running). This makes the UI switch between the started and stopped state incorrectly for a moemtn after pressing the connect button.

**Environment information:**
- OS: Linux

**Steps to Reproduce**

- Open the VPN UI, open the network tab of the browser dev tools, select a valid server and press the connect button, to start the VPN.
- In the browser dev tools you will see a call to `api/visors/{pk}/apps/vpn-client`. The response of that call is `2`, which is not really adecuate, as it is indicating that the app was stopped due to an error. This happens no matter if the app was stopped the last time due to an error or not.
- After that call, there are several calls to `/api/visors/{pk}/summary`, made every few seconds. The first call returns `0` as the status of the vpn-client app, which menas that the app is stopped, so the VPN UI returns to the disconnected state for a moment.
- After a moment, the calls to `/api/visors/{pk}/summary` start returning `1` as the status of the vpn-client app. That is the moment when the UI starts showing the VPN as running.

**Actual behavior**
This behavior is making the UI switch between started and stopped a couple of times after pressing the connect button, instead of staying in the started state.

A change can be done in the UI to try to prevent this, but there is no guarantee for it to work in all cases. As the status is checked every few moments and there are no real time events, the UI can not make assumptions about what the state of the vpn-client state is, as that would make it prone to errors in different situations. Becuse of this, a fix in the back-end would be best.

**Expected behavior**
Just after starting the app, the status should be 1

**Comment by ersonp** [comment]
Most of has issues mentioned have already been fixed. 
While testing I came across just one issue.
- Basically, whenever we start a vpn-client it takes a few mili secs for the app to start and before that happens if the summary is called then it returns `status` as 0 and the UI gets confused as the button was just pressed and the `state` that it got was 0. This happens 1/10 times. Also `Status: 1, DetailedStatus: Running` is usually returned in this case on the next summary call, instead of sending `Status: 1, DetailedStatus: Connecting` before sending ` Status: 1, DetailedStatus: Running` as it sends 9/10 times. 

So I think the UI should assume the `connecting` part till the time it gets either a `1` or `2` from the backend. What are your thoughts about it @Senyoret1 @jdknives ?
